spring:
  jackson:
    default-property-inclusion:  non_null #全局jackson不对null做序列化输出
  application:
    name: article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.185.35:3306/videoblog-article?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wll2001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        flow-ds: #sentinel从nacos获取指定的流控规则
          nacos:
            server-addr: localhost:8848 #nacos地址
            dataId: article-service-flow-rules #data id (nacos的配置列表中所对应的data id)
            groupId: DEFAULT_GROUP #分组
            ruleType: flow #flow代表流控规则
            username: nacos #用户名
            password: nacos #密码
        grade-ds: #sentinel从nacos获取指定的熔断规则
          nacos:
            server-addr: localhost:8848 #nacos地址
            dataId: article-service-degrade-rules #data id (nacos的配置列表中所对应的data id)
            groupId: DEFAULT_GROUP #分组
            ruleType: degrade #degrade代表熔断规则
            username: nacos #用户名
            password: nacos #密码

server:
  port: 2000
mybatis:
  config-location: classpath:/db/mybatis-config.xml
#startup.cmd -m standalone
feign:
  client:
    config:
      default:
        loggerLevel: HEADERS #将每一次openfeign请求的头信息在日志输出
  sentinel:
    enabled: true  #sentinel整合openfeign#开启基于Sentinel(限流熔断组件)的openfeign(实现服务间rest通信)调用限流熔断
management: #设置默认对外暴露哪些健康检查项,默认*检查全部
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    admin: debug
